version: '3.8'

services:
  # MySQL主从集群
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: campus_enrollment
    ports:
      - "3306:3306"
    volumes:
      - mysql_master_data:/var/lib/mysql
      - ./config/mysql/master.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - campus-network

  mysql-slave1:
    image: mysql:8.0
    container_name: mysql-slave1
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - mysql_slave1_data:/var/lib/mysql
      - ./config/mysql/slave1.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - campus-network
    depends_on:
      - mysql-master

  # Redis集群
  redis-node1:
    image: redis:6.2
    container_name: redis-node1
    ports:
      - "6379:6379"
    volumes:
      - redis_node1_data:/data
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf
    networks:
      - campus-network

  redis-node2:
    image: redis:6.2
    container_name: redis-node2
    volumes:
      - redis_node2_data:/data
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf
    networks:
      - campus-network

  # Kafka集群
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - campus-network

  kafka1:
    image: confluentinc/cp-kafka:7.0.0
    container_name: kafka1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
    ports:
      - "9092:9092"
    networks:
      - campus-network

  # 应用服务
  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - campus-network
    depends_on:
      - mysql-master
      - redis-node1

  enrollment-service:
    build: ./services/enrollment-service
    container_name: enrollment-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - campus-network
    depends_on:
      - mysql-master
      - redis-node1
      - kafka1

  # 监控系统
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - campus-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    networks:
      - campus-network
    depends_on:
      - prometheus

volumes:
  mysql_master_data:
  mysql_slave1_data:
  redis_node1_data:
  redis_node2_data:

networks:
  campus-network:
    driver: bridge
